osx_image: xcode9
language: Objective-C
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac
script:
  - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme BricBrac
  - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme Curio

after_success:
  - bash <(curl -s https://codecov.io/bash)

